version: '2.4'
services:
  mpd:
    image: tobi312/rpi-mpd:alpine
    container_name: "ddev-${DDEV_SITENAME}-mpd"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    restart: unless-stopped
    ports:
      - 6600:6600  # MPD Client
      - 8000:8000  # Stream
    volumes:
      - ./Music:/var/lib/mpd/music:rw
      - ./playlists:/var/lib/mpd/playlists:rw
      - ./data:/var/lib/mpd/data:rw
      #- ./mpd.conf:/etc/mpd.conf:rw
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
